name: Check for version bumps
author: Daniel Holz
description: Looks for changes to `CHANGELOG.md` & a `version` file in a PR, and fails if it can't find both.

inputs:
  pr-number:
    description: 'PR to look at for changed files'
    required: true

runs:
  using: composite
  steps:
    - env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        bash -x "$GITHUB_ACTION_PATH"/src/check_version_bump.sh \
          "${{ github.repository }}" \
          "${{ inputs.pr-number }}"
