name: "BATS"

on: 
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: Test
        run: npm exec bats -r test
