name: "BATS"

on: 
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: bats -r test
