name: Check version & CHANGELOG bumped

on:
  workflow_call:

jobs:
  check-for-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check for version bump
        uses: dgholz/action-check-version-bump@v1.2.7
        with:
          pr-number: ${{ github.event.pull_request.number }}
